// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dsimplex_cpp
Rcpp::NumericVector dsimplex_cpp(const Rcpp::NumericVector& y, const Rcpp::NumericVector& mu, const Rcpp::NumericVector& phi, const bool log, const int n_threads);
RcppExport SEXP _fastsimplexreg_dsimplex_cpp(SEXP ySEXP, SEXP muSEXP, SEXP phiSEXP, SEXP logSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const bool >::type log(logSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(dsimplex_cpp(y, mu, phi, log, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// rsimplex_cpp
Rcpp::NumericVector rsimplex_cpp(const int n, const Rcpp::NumericVector& mu, const Rcpp::NumericVector& phi);
RcppExport SEXP _fastsimplexreg_rsimplex_cpp(SEXP nSEXP, SEXP muSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(rsimplex_cpp(n, mu, phi));
    return rcpp_result_gen;
END_RCPP
}
// simplex_eval_cpp
Rcpp::List simplex_eval_cpp(const arma::vec& theta, const arma::vec& y, const arma::mat& X, const arma::mat& Z, const int mean_link, const int n_threads);
RcppExport SEXP _fastsimplexreg_simplex_eval_cpp(SEXP thetaSEXP, SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP mean_linkSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int >::type mean_link(mean_linkSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(simplex_eval_cpp(theta, y, X, Z, mean_link, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// simplex_bfgs_cpp
Rcpp::List simplex_bfgs_cpp(const arma::vec& start, const arma::vec& y, const arma::mat& X, const arma::mat& Z, const int mean_link, const int maxit, const double rel_tol, const double grad_tol, const int n_threads, const bool trace);
RcppExport SEXP _fastsimplexreg_simplex_bfgs_cpp(SEXP startSEXP, SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP mean_linkSEXP, SEXP maxitSEXP, SEXP rel_tolSEXP, SEXP grad_tolSEXP, SEXP n_threadsSEXP, SEXP traceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int >::type mean_link(mean_linkSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type rel_tol(rel_tolSEXP);
    Rcpp::traits::input_parameter< const double >::type grad_tol(grad_tolSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const bool >::type trace(traceSEXP);
    rcpp_result_gen = Rcpp::wrap(simplex_bfgs_cpp(start, y, X, Z, mean_link, maxit, rel_tol, grad_tol, n_threads, trace));
    return rcpp_result_gen;
END_RCPP
}
// simplex_hessian_fd_cpp
arma::mat simplex_hessian_fd_cpp(const arma::vec& theta, const arma::vec& y, const arma::mat& X, const arma::mat& Z, const int mean_link, const double rel_step, const int n_threads);
RcppExport SEXP _fastsimplexreg_simplex_hessian_fd_cpp(SEXP thetaSEXP, SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP mean_linkSEXP, SEXP rel_stepSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int >::type mean_link(mean_linkSEXP);
    Rcpp::traits::input_parameter< const double >::type rel_step(rel_stepSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(simplex_hessian_fd_cpp(theta, y, X, Z, mean_link, rel_step, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// simplex_predict_cpp
Rcpp::List simplex_predict_cpp(const arma::vec& theta, const arma::mat& X, const arma::mat& Z, const int mean_link);
RcppExport SEXP _fastsimplexreg_simplex_predict_cpp(SEXP thetaSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP mean_linkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int >::type mean_link(mean_linkSEXP);
    rcpp_result_gen = Rcpp::wrap(simplex_predict_cpp(theta, X, Z, mean_link));
    return rcpp_result_gen;
END_RCPP
}
// simplex_linkinv_cpp
Rcpp::NumericVector simplex_linkinv_cpp(const Rcpp::NumericVector& eta, const int mean_link);
RcppExport SEXP _fastsimplexreg_simplex_linkinv_cpp(SEXP etaSEXP, SEXP mean_linkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const int >::type mean_link(mean_linkSEXP);
    rcpp_result_gen = Rcpp::wrap(simplex_linkinv_cpp(eta, mean_link));
    return rcpp_result_gen;
END_RCPP
}
// simplex_mixed_eval_cpp
Rcpp::List simplex_mixed_eval_cpp(const arma::vec& theta, const arma::vec& y, const arma::mat& X, const arma::mat& Z, const arma::mat& W, const arma::uvec& starts, const int q, const int mean_link, const int nAGQ, const int n_threads, const int inner_maxit, const double inner_tol);
RcppExport SEXP _fastsimplexreg_simplex_mixed_eval_cpp(SEXP thetaSEXP, SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP WSEXP, SEXP startsSEXP, SEXP qSEXP, SEXP mean_linkSEXP, SEXP nAGQSEXP, SEXP n_threadsSEXP, SEXP inner_maxitSEXP, SEXP inner_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const int >::type mean_link(mean_linkSEXP);
    Rcpp::traits::input_parameter< const int >::type nAGQ(nAGQSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type inner_maxit(inner_maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type inner_tol(inner_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(simplex_mixed_eval_cpp(theta, y, X, Z, W, starts, q, mean_link, nAGQ, n_threads, inner_maxit, inner_tol));
    return rcpp_result_gen;
END_RCPP
}
// simplex_mixed_bfgs_cpp
Rcpp::List simplex_mixed_bfgs_cpp(const arma::vec& start, const arma::vec& y, const arma::mat& X, const arma::mat& Z, const arma::mat& W, const arma::uvec& starts, const int q, const int mean_link, const int nAGQ, const int maxit, const double rel_tol, const double grad_tol, const int n_threads, const int inner_maxit, const double inner_tol, const bool trace);
RcppExport SEXP _fastsimplexreg_simplex_mixed_bfgs_cpp(SEXP startSEXP, SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP WSEXP, SEXP startsSEXP, SEXP qSEXP, SEXP mean_linkSEXP, SEXP nAGQSEXP, SEXP maxitSEXP, SEXP rel_tolSEXP, SEXP grad_tolSEXP, SEXP n_threadsSEXP, SEXP inner_maxitSEXP, SEXP inner_tolSEXP, SEXP traceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type start(startSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const int >::type mean_link(mean_linkSEXP);
    Rcpp::traits::input_parameter< const int >::type nAGQ(nAGQSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type rel_tol(rel_tolSEXP);
    Rcpp::traits::input_parameter< const double >::type grad_tol(grad_tolSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type inner_maxit(inner_maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type inner_tol(inner_tolSEXP);
    Rcpp::traits::input_parameter< const bool >::type trace(traceSEXP);
    rcpp_result_gen = Rcpp::wrap(simplex_mixed_bfgs_cpp(start, y, X, Z, W, starts, q, mean_link, nAGQ, maxit, rel_tol, grad_tol, n_threads, inner_maxit, inner_tol, trace));
    return rcpp_result_gen;
END_RCPP
}
// simplex_mixed_hessian_fd_cpp
arma::mat simplex_mixed_hessian_fd_cpp(const arma::vec& theta, const arma::vec& y, const arma::mat& X, const arma::mat& Z, const arma::mat& W, const arma::uvec& starts, const int q, const int mean_link, const int nAGQ, const double rel_step, const int n_threads, const int inner_maxit, const double inner_tol);
RcppExport SEXP _fastsimplexreg_simplex_mixed_hessian_fd_cpp(SEXP thetaSEXP, SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP WSEXP, SEXP startsSEXP, SEXP qSEXP, SEXP mean_linkSEXP, SEXP nAGQSEXP, SEXP rel_stepSEXP, SEXP n_threadsSEXP, SEXP inner_maxitSEXP, SEXP inner_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const int >::type mean_link(mean_linkSEXP);
    Rcpp::traits::input_parameter< const int >::type nAGQ(nAGQSEXP);
    Rcpp::traits::input_parameter< const double >::type rel_step(rel_stepSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type inner_maxit(inner_maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type inner_tol(inner_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(simplex_mixed_hessian_fd_cpp(theta, y, X, Z, W, starts, q, mean_link, nAGQ, rel_step, n_threads, inner_maxit, inner_tol));
    return rcpp_result_gen;
END_RCPP
}
// simplex_mixed_ranef_cpp
Rcpp::List simplex_mixed_ranef_cpp(const arma::vec& theta, const arma::vec& y, const arma::mat& X, const arma::mat& Z, const arma::mat& W, const arma::uvec& starts, const int q, const int mean_link, const int n_threads, const int inner_maxit, const double inner_tol);
RcppExport SEXP _fastsimplexreg_simplex_mixed_ranef_cpp(SEXP thetaSEXP, SEXP ySEXP, SEXP XSEXP, SEXP ZSEXP, SEXP WSEXP, SEXP startsSEXP, SEXP qSEXP, SEXP mean_linkSEXP, SEXP n_threadsSEXP, SEXP inner_maxitSEXP, SEXP inner_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const int >::type mean_link(mean_linkSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const int >::type inner_maxit(inner_maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type inner_tol(inner_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(simplex_mixed_ranef_cpp(theta, y, X, Z, W, starts, q, mean_link, n_threads, inner_maxit, inner_tol));
    return rcpp_result_gen;
END_RCPP
}
// simplex_mixed_predict_cpp
Rcpp::List simplex_mixed_predict_cpp(const arma::vec& theta, const arma::mat& X, const arma::mat& Z, const arma::mat& W, const arma::uvec& starts, const int q, const arma::mat& b, const int mean_link, const bool include_re);
RcppExport SEXP _fastsimplexreg_simplex_mixed_predict_cpp(SEXP thetaSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP WSEXP, SEXP startsSEXP, SEXP qSEXP, SEXP bSEXP, SEXP mean_linkSEXP, SEXP include_reSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const int >::type mean_link(mean_linkSEXP);
    Rcpp::traits::input_parameter< const bool >::type include_re(include_reSEXP);
    rcpp_result_gen = Rcpp::wrap(simplex_mixed_predict_cpp(theta, X, Z, W, starts, q, b, mean_link, include_re));
    return rcpp_result_gen;
END_RCPP
}
// simplex_mixed_D_from_omega_cpp
arma::mat simplex_mixed_D_from_omega_cpp(const arma::vec& omega, const int q);
RcppExport SEXP _fastsimplexreg_simplex_mixed_D_from_omega_cpp(SEXP omegaSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< const int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(simplex_mixed_D_from_omega_cpp(omega, q));
    return rcpp_result_gen;
END_RCPP
}
// simplex_mixed_omega_from_D_cpp
arma::vec simplex_mixed_omega_from_D_cpp(const arma::mat& D);
RcppExport SEXP _fastsimplexreg_simplex_mixed_omega_from_D_cpp(SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(simplex_mixed_omega_from_D_cpp(D));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastsimplexreg_dsimplex_cpp", (DL_FUNC) &_fastsimplexreg_dsimplex_cpp, 5},
    {"_fastsimplexreg_rsimplex_cpp", (DL_FUNC) &_fastsimplexreg_rsimplex_cpp, 3},
    {"_fastsimplexreg_simplex_eval_cpp", (DL_FUNC) &_fastsimplexreg_simplex_eval_cpp, 6},
    {"_fastsimplexreg_simplex_bfgs_cpp", (DL_FUNC) &_fastsimplexreg_simplex_bfgs_cpp, 10},
    {"_fastsimplexreg_simplex_hessian_fd_cpp", (DL_FUNC) &_fastsimplexreg_simplex_hessian_fd_cpp, 7},
    {"_fastsimplexreg_simplex_predict_cpp", (DL_FUNC) &_fastsimplexreg_simplex_predict_cpp, 4},
    {"_fastsimplexreg_simplex_linkinv_cpp", (DL_FUNC) &_fastsimplexreg_simplex_linkinv_cpp, 2},
    {"_fastsimplexreg_simplex_mixed_eval_cpp", (DL_FUNC) &_fastsimplexreg_simplex_mixed_eval_cpp, 12},
    {"_fastsimplexreg_simplex_mixed_bfgs_cpp", (DL_FUNC) &_fastsimplexreg_simplex_mixed_bfgs_cpp, 16},
    {"_fastsimplexreg_simplex_mixed_hessian_fd_cpp", (DL_FUNC) &_fastsimplexreg_simplex_mixed_hessian_fd_cpp, 13},
    {"_fastsimplexreg_simplex_mixed_ranef_cpp", (DL_FUNC) &_fastsimplexreg_simplex_mixed_ranef_cpp, 11},
    {"_fastsimplexreg_simplex_mixed_predict_cpp", (DL_FUNC) &_fastsimplexreg_simplex_mixed_predict_cpp, 9},
    {"_fastsimplexreg_simplex_mixed_D_from_omega_cpp", (DL_FUNC) &_fastsimplexreg_simplex_mixed_D_from_omega_cpp, 2},
    {"_fastsimplexreg_simplex_mixed_omega_from_D_cpp", (DL_FUNC) &_fastsimplexreg_simplex_mixed_omega_from_D_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastsimplexreg(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
